version: '3.8'

services:
  backend:
    build:
      context: ./python_backend_api
      dockerfile: Dockerfile
    container_name: escomic-backend
    ports:
      - "8000:8000"
    volumes:
      - ./python_backend_api/:/api
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - escomic_network

  frontend:
    build:
      context: ./react_frontend_ui
      dockerfile: Dockerfile
    container_name: escomic-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react_frontend_ui/:/app
      - "escomic_volume:/app/node_modules"
    depends_on:
      - backend
    networks:
      - escomic_network

volumes:
  escomic_volume:

networks:
  escomic_network:
    driver: bridge
